export interface EyeCondition {
  slug: string;
  name: string;
  shortDesc: string;
  overview: string;
  symptoms: string[];
  causes: string[];
  treatments: string[];
  whenToSeeDoctor: string;
  swahili: {
    overview: string;
    symptoms: string[];
    causes: string[];
    treatments: string[];
    whenToSeeDoctor: string;
  };
}

export const eyeConditions: EyeCondition[] = [
  {
    slug: "strabismus",
    name: "Strabismus",
    shortDesc: "A condition where the eyes do not properly align with each other when looking at an object.",
    overview:
      "Strabismus, commonly known as a squint or crossed eyes, is a condition where the eyes do not properly align with each other when looking at an object. One eye may turn inwards, outwards, upwards, or downwards while the other eye looks straight ahead. This misalignment can be constant or intermittent and may affect one or both eyes. Strabismus is one of the most common eye conditions in children, affecting approximately 2-4% of the population. If left untreated, particularly in children, it can lead to amblyopia (lazy eye), where the brain ignores signals from the affected eye, resulting in permanent vision loss in that eye. Early diagnosis and treatment are essential to preserve vision and restore proper eye alignment.",
    symptoms: [
      "Eyes that appear to point in different directions",
      "Double vision (diplopia)",
      "Blurred vision",
      "Eyes that do not move together",
      "Squinting or closing one eye in bright sunlight",
      "Tilting the head to look at things",
      "Poor depth perception",
      "Eye strain or headaches",
    ],
    causes: [
      "Problems with the eye muscles that control movement",
      "Nerve problems affecting the eye muscles",
      "Genetics and family history of strabismus",
      "Refractive errors such as long-sightedness",
      "Medical conditions such as cerebral palsy or Down syndrome",
      "Eye injuries or trauma",
      "Brain tumors or other neurological conditions",
      "Stroke or other vascular problems affecting the brain",
    ],
    treatments: [
      "Glasses or contact lenses to correct refractive errors",
      "Eye exercises and vision therapy to strengthen eye coordination",
      "Prism lenses to reduce double vision",
      "Botulinum toxin (Botox) injections to relax overactive eye muscles",
      "Eye muscle surgery to adjust the length or position of eye muscles",
      "Patching the stronger eye to treat associated amblyopia",
      "Atropine eye drops as an alternative to patching for amblyopia",
    ],
    whenToSeeDoctor:
      "You should see an eye specialist if you notice any misalignment of your child's eyes, if you experience double vision, or if you have difficulty with depth perception. For children, early screening is crucial — all children should have their eyes checked by age 3, or earlier if there is a family history of strabismus or amblyopia. Adults who develop sudden strabismus should seek immediate medical attention, as this may indicate a serious underlying condition such as a stroke or brain tumor.",
    swahili: {
      overview:
        "Strabismus, maarufu kama cross-eye au squint, ni hali ambayo macho hayalingani vizuri wakati wa kutazama kitu. Jicho moja linaweza kuelekea ndani, nje, juu au chini wakati jicho lingine linatazama mbele. Hali hii inaweza kuwa ya kudumu au ya mara kwa mara na inaweza kuathiri jicho moja au macho yote mawili. Strabismus ni moja ya hali za macho zilizo za kawaida zaidi kwa watoto, ikiaathiri asilimia 2-4 ya idadi ya watu. Ikiitaachwa bila matibabu, hasa kwa watoto, inaweza kusababisha amblyopia (jicho lenye uvivu), ambapo ubongo hupuuza ishara kutoka kwa jicho lililoathirika, ikisababisha upotevu wa uwezo wa kuona wa kudumu. Utambuzi na matibabu mapema ni muhimu kuokoa uwezo wa kuona na kurejesha mpangilio sahihi wa macho.",
      symptoms: [
        "Macho yanayoonekana kuelekea katika mwelekeo tofauti",
        "Kuona mara mbili (diplopia)",
        "Kupata waziwazi",
        "Macho ambayo hayahamii pamoja",
        "Kufunga jicho moja wakati wa jua kali",
        "Kuinua kichwa kutazama vitu",
        "Kushindwa kutambua umbali",
        "Mashaka ya macho au maumivu ya kichwa",
      ],
      causes: [
        "Matatizo ya misuli ya jicho inayodhibiti mwendo",
        "Matatizo ya neva yanayoathiri misuli ya jicho",
        "Urithi na historia ya familia ya strabismus",
        "Makosa ya kupima kama vile kuona mbali",
        "Hali za kiafya kama vile cerebral palsy au Down syndrome",
        "Majeraha ya jicho",
        "Vimbe vya ubongo au hali zingine za neva",
        "Kiharusi au matatizo mengine ya mishipa ya damu yanayoathiri ubongo",
      ],
      treatments: [
        "Miwani au lens za mawasiliano kurekebisha makosa ya kupima",
        "Mazoezi ya macho na tiba ya kuona kuimarisha ushirikiano wa macho",
        "Miwani ya prism kupunguza kuona mara mbili",
        "Sindano za Botox kupumzisha misuli ya macho inayoathirika",
        "Upasuaji wa misuli ya jicho kurekebisha urefu au mahali pa misuli ya jicho",
        "Kufunika jicho lenye nguvu kutibu amblyopia inayohusiana",
        "Majasho ya atropine kama mbadala wa kufunika kwa ajili ya amblyopia",
      ],
      whenToSeeDoctor:
        "Unapaswa kuona mtaalamu wa macho ikiwa unaona mpangilio wowote usio sahihi wa macho ya mtoto wako, ikiwa unaona mara mbili, au ikiwa una shida kutambua umbali. Kwa watoto, ukaguzi mapema ni muhimu — watoto wote wanapaswa kuangaliwa macho hadi umri wa miaka 3, au mapema ikiwa kuna historia ya familia ya strabismus au amblyopia. Watu wazima wanaopata strabiscus ghafla wanapaswa kutafuta matibabu ya haraka, kwani hii inaweza kuonyesha hali ya msingi kama vile kiharusi au uvimbe wa ubongo.",
    },
  },
  {
    slug: "cataract",
    name: "Cataract",
    shortDesc: "A clouding of the normally clear lens of the eye, leading to decreased vision.",
    overview:
      "A cataract is a clouding of the normally clear lens of the eye. For people who have cataracts, seeing through cloudy lenses is a bit like looking through a frosty or fogged-up window. Clouded vision caused by cataracts can make it more difficult to read, drive a car (especially at night), or see the expression on a friend's face. Most cataracts develop slowly and don't disturb eyesight early on. But with time, cataracts will eventually interfere with vision. At first, stronger lighting and eyeglasses can help deal with cataracts. But if impaired vision interferes with usual activities, cataract surgery is recommended. Fortunately, cataract surgery is generally a safe, effective procedure.",
    symptoms: [
      "Clouded, blurred, or dim vision",
      "Increasing difficulty with vision at night",
      "Sensitivity to light and glare",
      "Need for brighter light for reading and other activities",
      "Seeing 'halos' around lights",
      "Frequent changes in eyeglass or contact lens prescription",
      "Fading or yellowing of colors",
      "Double vision in a single eye",
    ],
    causes: [
      "Aging — most cataracts develop as a result of normal age-related changes",
      "Ultraviolet radiation from sunlight and other sources",
      "Diabetes and other metabolic disorders",
      "Prolonged use of corticosteroid medications",
      "Previous eye injury or inflammation",
      "Previous eye surgery",
      "Smoking and excessive alcohol consumption",
      "Family history of cataracts",
      "Obesity",
      "High blood pressure",
    ],
    treatments: [
      "Stronger eyeglasses or magnifying lenses for early-stage cataracts",
      "Improved lighting at home and work",
      "Anti-glare sunglasses for light sensitivity",
      "Cataract surgery — the only effective treatment for advanced cataracts",
      "Phacoemulsification (small-incision ultrasound surgery)",
      "Extracapsular cataract extraction for advanced cataracts",
      "Intraocular lens (IOL) implantation to replace the clouded lens",
      "Laser-assisted cataract surgery for enhanced precision",
    ],
    whenToSeeDoctor:
      "You should make an appointment for an eye exam if you notice any changes in your vision, such as clouding, blurring, or increased glare. If you develop sudden vision changes, such as double vision or flashes of light, sudden eye pain, or a sudden headache, see your doctor right away. For adults over 60, it is recommended to have a comprehensive eye exam at least every two years, even if you have no symptoms, as cataracts can develop without noticeable early signs.",
    swahili: {
      overview:
        "Cataract ni kuvimbiwa kwa lensi ya jicho ambayo kwa kawaida ni wazi. Kwa watu wenye cataracts, kuona kupitia lensi zenye vimvi ni kama kutazama kupitia dirisha lililofunikwa na barafu au ukungu. Kuona vilivyo vimbi kutokana na cataract kunaweza kufanya kuwe vigumu kusoma, kuendesha gari (hasa usiku), au kuona usemi wa uso wa rafiki. Cataracts nyingi hukua polepole na hazisumbui uwezo wa kuona mapema. Lakini kwa muda, cataracts hatimaye zitasumbua kuona. Kwanza, taa kali zaidi na miwani inaweza kusaidia kushughulikia cataracts. Lakini ikiwa kuona kuharibika kunasumbua shughuli za kawaida, upasuaji wa cataract unashauriwa. Kwa bahati nzuri, upasuaji wa cataract kwa ujumla ni mchakato salama na wenye ufanisi.",
      symptoms: [
        "Kuona kama kuna wingu, kupata waziwazi, au kuona giza",
        "Ugumu wa kuona usiku unaongezeka",
        "Kuhisia mwanga mwingi au kutoa mng'ao",
        "Haja ya taa kali zaidi kusoma na shughuli nyingine",
        "Kuona 'mabara' ya nuru",
        "Mabadiliko ya mara kwa mara ya dawa ya miwani au lens za mawasiliano",
        "Rangi kufifia au kuingia manjano",
        "Kuona mara mbili katika jicho moja",
      ],
      causes: [
        "Kuzeeka — cataracts nyingi hukua kutokana na mabadiliko ya kawaida yanayohusiana na umri",
        "Mnururisho wa ultraviolet kutoka kwa jua na vyanzo vingine",
        "Kisukari na magonjwa mengine ya kimetaboliki",
        "Matumizi ya muda mrefu ya dawa za kortikositeroidi",
        "Majeraha ya jicho au uvimbi uliopita",
        "Upasuaji wa jicho uliopita",
        "Kuvuta sigara na matumizi ya pombe kupita kiasi",
        "Historia ya familia ya cataracts",
        "Uzito kupita kiasi",
        "Shinikizo la damu kupita kiasi",
      ],
      treatments: [
        "Miwani yenye nguvu zaidi au lens za kukuza kwa cataracts za awali",
        "Taa bora zaidi nyumbani na kazini",
        "Miwani ya kupunguza mng'ao kwa wasumbufu wa nuru",
        "Upasuaji wa cataract — matibabu pekee yanayofaa kwa cataracts zilizoendelea",
        "Phacoemulsification (upasuaji wa ultrasound kwa kipindi kidogo)",
        "Uondoaji wa extracapsular kwa cataracts zilizoendelea",
        "Uingizwaji wa lens ya ndani ya jicho (IOL) kuchukua nafasi ya lens iliyovimbiwa",
        "Upasuaji wa cataract uliosaidiwa na laser kwa usahihi zaidi",
      ],
      whenToSeeDoctor:
        "Unapaswa kufanya miadi kwa uchunguzi wa macho ikiwa unaona mabadiliko yoyote katika uwezo wako wa kuona, kama vile kuvimbiwa, kupata waziwazi, au kuongezeka kwa mng'ao. Ikiwa unapata mabadiliko ghafla ya kuona, kama vile kuona mara mbili au miale ya nuru, maumivu ghafla ya jicho, au maumivu ya kichwa, ona daktari mara moja. Kwa watu wazima wenye umri zaidi ya miaka 60, inashauriwa kufanya uchunguzi kamili wa macho angalau kila miaka miwili, hata ikiwa huna dalili, kwani cataracts zinaweza kukua bila ishara za mapema zinazohisiwa.",
    },
  },
  {
    slug: "conjunctivitis",
    name: "Conjunctivitis",
    shortDesc: "Inflammation of the conjunctiva, the thin clear tissue that lies over the white part of the eye.",
    overview:
      "Conjunctivitis, commonly known as pink eye, is an inflammation of the conjunctiva — the thin, clear tissue that lies over the white part of the eye and lines the inside of the eyelid. It is one of the most common and treatable eye conditions in both children and adults. Conjunctivitis can be caused by viruses, bacteria, allergens, or irritants. While viral and bacterial conjunctivitis are highly contagious and can spread easily through direct or indirect contact with the eye secretions of an infected person, allergic conjunctivitis is not contagious. Most cases are mild and will clear up on their own within a few days to two weeks, but some forms may require medical treatment to prevent complications and reduce spread.",
    symptoms: [
      "Redness in one or both eyes",
      "Itchiness in one or both eyes",
      "A gritty feeling in one or both eyes",
      "A discharge in one or both eyes that forms a crust during the night",
      "Tearing",
      "Sensitivity to light",
      "Swelling of the conjunctiva or eyelids",
      "Burning sensation",
    ],
    causes: [
      "Viruses — the same viruses that cause the common cold",
      "Bacteria such as Staphylococcus aureus, Streptococcus pneumoniae, or Haemophilus influenzae",
      "Allergens such as pollen, dust mites, mold, or pet dander",
      "Irritants such as chlorine in swimming pools, smoke, or foreign objects",
      "Contact lens wear, especially extended-wear lenses",
      "Chemicals or fumes in the environment",
      "Sexually transmitted infections such as chlamydia or gonorrhea in newborns",
      "Blocked tear duct in newborns",
    ],
    treatments: [
      "Viral conjunctivitis usually resolves on its own within 7-14 days; cold compresses can help relieve discomfort",
      "Bacterial conjunctivitis is treated with antibiotic eye drops or ointments",
      "Antihistamine eye drops or oral medications for allergic conjunctivitis",
      "Anti-inflammatory eye drops for severe inflammation",
      "Artificial tears to soothe irritation and flush out allergens",
      "Avoiding contact lenses until the infection clears",
      "Good hygiene practices: frequent hand washing, avoiding eye rubbing, and not sharing towels or cosmetics",
      "Warm compresses to loosen crusted discharge",
    ],
    whenToSeeDoctor:
      "Seek medical care if you have moderate to severe eye pain, vision problems, intense redness, or symptoms that worsen or don't improve within 24 hours of beginning treatment. Newborns with symptoms of conjunctivitis should be seen by a doctor immediately, as the condition can be serious and vision-threatening. Contact lens wearers should also seek prompt care, as some infections can progress rapidly and threaten vision if not treated quickly.",
    swahili: {
      overview:
        "Conjunctivitis, maarufu kama pink eye, ni uvimbi wa conjunctiva — tishu nyembamba na wazi iliyo juu ya sehemu nyeupe ya jicho na inayopakana na ndani ya kiwembe cha jicho. Ni moja ya hali za macho zilizo za kawaida zaidi na zinazoweza kutibiwa kwa watoto na watu wazima. Conjunctivitis inaweza kusababishwa na virusi, bakteria, viambukizo, au visumbufu. Wakati conjunctivitis ya virusi na bakteria inaweza kuambukizwa kwa urahisi kupitia mawasiliano ya moja kwa moja au ya kisicho cha moja kwa moja na majasho ya jicho ya mtu aliyeambukizwa, conjunctivitis ya kiambukizo haiambukizi. Kesi nyingi ni nyepesi na zitapona peke yake ndani ya siku chache hadi wiki mbili, lakini aina zingine zinaweza kuhitaji matibabu ya kiafya kuzuia matatizo na kupunguza uenezi.",
      symptoms: [
        "Uekundu katika jicho moja au macho yote mawili",
        "Kuwashwa katika jicho moja au macho yote mawili",
        "Hisia ya kikwazo katika jicho moja au macho yote mawili",
        "Jasho katika jicho moja au macho yote mawili linaloanza kutoa g hardened wakati wa usiku",
        "Machozi",
        "Kuhisia mwanga",
        "Kuvimba kwa conjunctiva au viwembe vya macho",
        "Hisia ya kuchoma",
      ],
      causes: [
        "Virusi — virusi zilezile zinazosababisha mafua ya kawaida",
        "Bakteria kama vile Staphylococcus aureus, Streptococcus pneumoniae, au Haemophilus influenzae",
        "Viambukizo kama vile vumbi la maua, vumbi la nyumba, ukungu, au manyoya ya wanyama kipenzi",
        "Visumbufu kama vile klorini katika bwawa la kuogelea, moshi, au vitu vya kigeni",
        "Kuvaa lens za mawasiliano, hasa lens zilizochukuliwa muda mrefu",
        "Kemikali au moshi katika mazingira",
        "Mambukizo ya ngono kama vile chlamydia au gonorrhea kwa watoto wachanga",
        "Kuzuia kwa njia ya machozi kwa watoto wachanga",
      ],
      treatments: [
        "Conjunctivitis ya virusi kwa kawaida hupona peke yake ndani ya siku 7-14; compress za baridi zinaweza kusaidia kupunguza usumbufu",
        "Conjunctivitis ya bakteria inatibiwa na majasho ya antibayotiki au mafuta",
        "Majasho ya antihistamine au dawa za kumeza kwa conjunctivitis ya kiambukizo",
        "Majasho ya kupunguza uvimbi kwa uvimbi mkali",
        "Machozi ya bandia kupumzisha usumbufu na kuosha viambukizo",
        "Kuepuka lens za mawasiliano hadi maambukizo yapone",
        "Mazoea mazuri ya usafi: kunawa mikono mara kwa mara, kuepuka kuchubua macho, na kushiriki taulo au vipodozi",
        "Compress za joto kufungua majasho yaliyogandamana",
      ],
      whenToSeeDoctor:
        "Tafuta huduma ya kiafya ikiwa una maumivu ya wastani hadi makali ya jicho, matatizo ya kuona, uekundu mkali, au dalili zinazozidi kuwa mbaya au haziboreki ndani ya masaa 24 ya kuanza matibabu. Watoto wachanga wenye dalili za conjunctivitis wanapaswa kuona daktari mara moja, kwani hali hii inaweza kuwa hatari na kutishia uwezo wa kuona. Watumiaji wa lens za mawasiliano pia wanapaswa kutafuta matibabu ya haraka, kwani baadhi ya maambukizo yanaweza kuendelea kwa kasi na kutishia kuona ikiwa hayatibiwa haraka.",
    },
  },
  {
    slug: "diabetic-retinopathy",
    name: "Diabetic Retinopathy",
    shortDesc: "A diabetes complication that affects the eyes, caused by damage to blood vessels of the retina.",
    overview:
      "Diabetic retinopathy is a diabetes complication that affects the eyes. It is caused by damage to the blood vessels of the light-sensitive tissue at the back of the eye (retina). At first, diabetic retinopathy may cause no symptoms or only mild vision problems. But eventually, it can cause blindness. The condition can develop in anyone who has type 1 or type 2 diabetes. The longer you have diabetes and the less controlled your blood sugar is, the more likely you are to develop this eye complication. Diabetic retinopathy is the leading cause of blindness among working-age adults. Regular eye exams and good management of blood sugar, blood pressure, and cholesterol can prevent or delay vision loss.",
    symptoms: [
      "Spots or dark strings floating in your vision (floaters)",
      "Blurred vision",
      "Fluctuating vision",
      "Impaired color vision",
      "Dark or empty areas in your vision",
      "Vision loss",
      "Difficulty seeing at night",
      "Partial or total blindness in severe cases",
    ],
    causes: [
      "Prolonged high blood sugar levels damaging retinal blood vessels",
      "High blood pressure compounding blood vessel damage",
      "High cholesterol levels",
      "Duration of diabetes — risk increases the longer you have diabetes",
      "Poor blood sugar control",
      "Pregnancy in women with diabetes",
      "Tobacco use",
      "Genetic predisposition",
    ],
    treatments: [
      "Anti-VEGF injections into the eye (e.g., ranibizumab, aflibercept, bevacizumab)",
      "Focal laser treatment (photocoagulation) to stop or slow leakage of blood and fluid",
      "Scatter laser treatment (panretinal photocoagulation) to shrink abnormal blood vessels",
      "Vitrectomy surgery to remove blood and scar tissue from the vitreous gel",
      "Corticosteroid injections or implants",
      "Tight control of blood sugar, blood pressure, and cholesterol levels",
      "Regular comprehensive dilated eye exams",
      "Low vision aids and rehabilitation services",
    ],
    whenToSeeDoctor:
      "If you have diabetes, you should have a comprehensive dilated eye exam at least once a year, even if your vision seems fine. Contact your eye doctor immediately if you experience sudden vision changes, increased floaters, blurred vision, or any vision loss. Women with diabetes who are pregnant or planning pregnancy should have an eye exam before conception and during the first trimester, as pregnancy can worsen diabetic retinopathy.",
    swahili: {
      overview:
        "Ugonjwa wa retina wa kisukari ni matatizo ya kisukari yanayoathiri macho. Unasababishwa na uharibifu wa mishipa ya damu ya tishu inayohisi nuru nyuma ya jicho (retina). Mwanzoni, ugonjwa wa retina wa kisukari unaweza kusababisha dalili zozote au matatizo ya kuona tu. Lakini hatimaye, unaweza kusababisha upofu. Hali hii inaweza kukua kwa mtu yeyote mwenye kisukari cha aina ya 1 au 2. Kwa muda mrefu unaokuwa na kisukari na kwa kudhibiti sukari yako kidogo, ndivyo uwezekano wako wa kupata matatizo haya ya jicho unaongezeka. Ugonjwa wa retina wa kisukari ni sababu kuu ya upofu kati ya watu wazima wenye umri wa kufanya kazi. Uchunguzi mara kwa mara wa macho na usimamizi mzuri wa sukari, shinikizo la damu, na kolesterol unaweza kuzuia au kuahirisha upotevu wa uwezo wa kuona.",
      symptoms: [
        "Madoadoa au mistari ya giza inayozunguka katika kuona kwako (floaters)",
        "Kuona kama kuna wingu",
        "Kugeuka kwa kuona",
        "Uwezo wa kuona rangi uliopungua",
        "Maeneo meusi au matupu katika kuona kwako",
        "Upotevu wa uwezo wa kuona",
        "Ugumu wa kuona usiku",
        "Upofu wa sehemu au wa kila mahali katika kesi kali",
      ],
      causes: [
        "Kiwango cha juu cha sukari kwa muda mrefu kiharibu mishipa ya damu ya retina",
        "Shinikizo la juu la damu likiongeza uharibifu wa mishipa ya damu",
        "Kiwango cha juu cha kolesterol",
        "Muda wa kisukari — hatari huongezeka kwa muda mrefu unaokuwa na kisukari",
        "Udhibiti mbaya wa kiwango cha sukari",
        "Mimba kwa wanawake wenye kisukari",
        "Matumizi ya tumbaku",
        "Urithi wa kuzaliwa nao",
      ],
      treatments: [
        "Sindano za anti-VEGF ndani ya jicho (mfano, ranibizumab, aflibercept, bevacizumab)",
        "Matibabu ya laser ya sehemu (photocoagulation) kusimamisha au kupunguza kuvuja damu na maji",
        "Matibabu ya laser ya kupanga (panretinal photocoagulation) kupunguza mishipa ya damu isiyo ya kawaida",
        "Upasuaji wa vitrectomy kuondoa damu na tishu ya mafuta kutoka kwa jeli ya vitreous",
        "Sindano za corticosteroid au vifaa vya kuingizwa",
        "Udhibiti mkubwa wa kiwango cha sukari, shinikizo la damu, na kolesterol",
        "Uchunguzi mara kwa mara kamili wa macho yaliyoanikwa",
        "Vifaa vya kuona chini na huduma za urekebishaji",
      ],
      whenToSeeDoctor:
        "Ikiwa una kisukari, unapaswa kufanya uchunguzi kamili wa macho yaliyoanikwa angalau mara moja kwa mwaka, hata ikiwa kuona kwako kunaonekana sawa. Wasiliana na daktari wako wa macho mara moja ikiwa unapata mabadiliko ghafla ya kuona, kuongezeka kwa floaters, kuona kama kuna wingu, au upotevu wowote wa uwezo wa kuona. Wanawake wenye kisukari wanaosubiri mimba au wanaopanga mimba wanapaswa kufanya uchunguzi wa macho kabla ya mimba na wakati wa trimester ya kwanza, kwani mimba inaweza kuworsen ugonjwa wa retina wa kisukari.",
    },
  },
  {
    slug: "dry-eye",
    name: "Dry Eye",
    shortDesc: "A condition that occurs when tears aren't able to provide adequate lubrication for the eyes.",
    overview:
      "Dry eye is a common condition that occurs when your tears aren't able to provide adequate lubrication for your eyes. This can happen either because you don't produce enough tears or because your tears evaporate too quickly. Tears are essential for maintaining the health of the front surface of the eye and for providing clear vision. Dry eye can make it difficult to perform everyday activities, such as reading, using a computer, or driving. It is more common in older adults, women (especially after menopause), and people who live in dry climates or spend a lot of time looking at screens. While dry eye can be a chronic condition, there are many treatments available to keep your eyes healthy and comfortable.",
    symptoms: [
      "A stinging, burning, or scratchy sensation in your eyes",
      "Stringy mucus in or around your eyes",
      "Sensitivity to light",
      "Eye redness",
      "A sensation of having something in your eyes",
      "Difficulty wearing contact lenses",
      "Difficulty with nighttime driving",
      "Watery eyes (the body's response to irritation)",
      "Blurred vision or eye fatigue",
    ],
    causes: [
      "Decreased tear production due to aging, medical conditions, or medications",
      "Increased tear evaporation from wind, smoke, or dry air",
      "Blinking less often, especially during prolonged screen use",
      "Eyelid problems such as ectropion or entropion",
      "Meibomian gland dysfunction affecting tear quality",
      "Hormonal changes, especially in women after menopause",
      "Autoimmune diseases such as Sjögren's syndrome, lupus, or rheumatoid arthritis",
      "Vitamin A deficiency",
      "Certain medications including antihistamines, decongestants, and antidepressants",
    ],
    treatments: [
      "Over-the-counter artificial tear drops and ointments",
      "Prescription eye drops such as cyclosporine (Restasis) or lifitegrast (Xiidra)",
      "Steroid eye drops for short-term inflammation control",
      "Punctal plugs to block tear drainage and retain moisture",
      "Warm compresses and eyelid massage for meibomian gland dysfunction",
      "Omega-3 fatty acid supplements",
      "Prescription medications to stimulate tear production",
      "Intense pulsed light (IPL) therapy for meibomian gland dysfunction",
      "Scleral contact lenses to protect and hydrate the eye surface",
    ],
    whenToSeeDoctor:
      "See your eye doctor if your symptoms persist for more than a few days, if over-the-counter drops don't provide relief, or if your symptoms are severe enough to interfere with daily activities. You should also seek care if you experience eye pain, significant redness, or changes in vision, as these could indicate a more serious underlying condition.",
    swahili: {
      overview:
        "Jicho kavu ni hali ya kawaida inayotokea wakati machozi yako hayawezi kutoa unyevu wa kutosha kwa macho yako. Hii inaweza kutokea ama kwa sababu hautengenezi machozi ya kutosha au kwa sababu machozi yako yanatoweka haraka sana. Machozi ni muhimu kudumisha afya ya uso wa mbele wa jicho na kutoa uwezo wa kuona wazi. Jicho kavu linaweza kufanya kuwe vigumu kufanya shughuli za kila siku, kama vile kusoma, kutumia kompyuta, au kuendesha gari. Ni ya kawaida zaidi kwa watu wazima, wanawake (hasa baada ya menopause), na watu wanaoshi katika mazingira makavu au wanaotumia muda mwingi kutazama skrini. Wakati jicho kavu linaweza kuwa hali ya muda mrefu, kuna matibabu mengi yanayopatikana kudumisha macho yako yenye afya na starehe.",
      symptoms: [
        "Hisia ya kuchoma, kuungua, au kuchubua katika macho yako",
        "Mte wa tegili katika au karibu na macho yako",
        "Kuhisia mwanga",
        "Uekundu wa jicho",
        "Hisia ya kuwa na kitu katika macho yako",
        "Ugumu wa kuvaa lens za mawasiliano",
        "Ugumu wa kuendesha gari usiku",
        "Machozi (jibu la mwili kwa usumbufu)",
        "Kuona kama kuna wingu au uchovu wa macho",
      ],
      causes: [
        "Upungufu wa utengenezwaji wa machozi kutokana na kuzeeka, hali za kiafya, au dawa",
        "Kuongezeka kwa kutoweka kwa machozi kutokana na upepo, moshi, au hewa kavu",
        "Kupiga jicho mara chache, hasa wakati wa kutumia skrini kwa muda mrefu",
        "Matatizo ya kiwembe cha jicho kama vile ectropion au entropion",
        "Kazi kufa ya tezi za Meibomian ikiaffect quality ya machozi",
        "Mabadiliko ya homoni, hasa kwa wanawake baada ya menopause",
        "Magonjwa ya autoimmune kama vile Sjögren's syndrome, lupus, au rheumatoid arthritis",
        "Upungufu wa Vitamini A",
        "Dawa fulani ikiwemo antihistamines, decongestants, na antidepressants",
      ],
      treatments: [
        "Majasho ya machozi ya bandia na mafuta yanayopatikana bila dawa",
        "Majasho ya dawa kama vile cyclosporine (Restasis) au lifitegrast (Xiidra)",
        "Majasho ya steroid kwa udhibiti mfupi wa uvimbi",
        "Plug za punctal kuzuia kupitisha maji ya machozi na kuhifadhi unyevu",
        "Compress za joto na kukanda kiwembe cha jicho kwa kazi kufa ya tezi za Meibomian",
        "Virutubisho vya Omega-3 fatty acid",
        "Dawa za daktari kuhamasisha utengenezwaji wa machozi",
        "Tiba ya nuru kali ya pulsed (IPL) kwa kazi kufa ya tezi za Meibomian",
        "Lens za scleral kulinda na kuunyevusha uso wa jicho",
      ],
      whenToSeeDoctor:
        "Ona daktari wako wa macho ikiwa dalili zako zinaendelea kwa zaidi ya siku chache, ikiwa majasho yanayopatikana bila dawa hayatoi nafuu, au ikiwa dalili zako ni kali kiasi cha kusumbua shughuli za kila siku. Unapaswa pia kutafuta matibabu ikiwa unapata maumivu ya jicho, uekundu mkubwa, au mabadiliko katika kuona, kwani hizi zinaweza kuonyesha hali ya msingi zaidi.",
    },
  },
  {
    slug: "glaucoma",
    name: "Glaucoma",
    shortDesc: "A group of eye conditions that damage the optic nerve, often caused by abnormally high pressure in the eye.",
    overview:
      "Glaucoma is a group of eye conditions that damage the optic nerve, the health of which is vital for good vision. This damage is often caused by abnormally high pressure in your eye. Glaucoma is one of the leading causes of blindness for people over the age of 60. It can occur at any age but is more common in older adults. Many forms of glaucoma have no warning signs. The effect is so gradual that you may not notice a change in vision until the condition is at an advanced stage. Because vision loss due to glaucoma can't be recovered, it's important to have regular eye exams that include measurements of your eye pressure so a diagnosis can be made in its early stages and treated appropriately. If glaucoma is recognized early, vision loss can be slowed or prevented.",
    symptoms: [
      "Patchy blind spots in your side (peripheral) or central vision, frequently in both eyes",
      "Tunnel vision in the advanced stages",
      "Severe headache",
      "Eye pain",
      "Nausea and vomiting",
      "Blurred vision",
      "Halos around lights",
      "Eye redness",
    ],
    causes: [
      "Elevated intraocular pressure due to fluid buildup in the eye",
      "Impaired drainage of aqueous humor through the trabecular meshwork",
      "Family history of glaucoma",
      "Age — people over 60 are at increased risk",
      "Medical conditions such as diabetes, heart disease, high blood pressure, and sickle cell anemia",
      "Extreme nearsightedness or farsightedness",
      "Eye injuries or certain types of eye surgery",
      "Long-term use of corticosteroid medications, especially eye drops",
      "Ethnicity — African Americans, Asians, and Hispanics are at higher risk",
    ],
    treatments: [
      "Prescription eye drops to reduce intraocular pressure",
      "Oral medications such as carbonic anhydrase inhibitors",
      "Laser trabeculoplasty to improve drainage",
      "Laser iridotomy for angle-closure glaucoma",
      "Minimally invasive glaucoma surgery (MIGS)",
      "Trabeculectomy to create a new drainage pathway",
      "Drainage tubes (shunts) to drain excess fluid",
      "Cyclodestructive procedures to reduce fluid production",
    ],
    whenToSeeDoctor:
      "Seek immediate medical attention if you experience sudden severe eye pain, headache, blurred vision, halos around lights, or nausea and vomiting — these may be signs of acute angle-closure glaucoma, which is a medical emergency. Otherwise, adults should have comprehensive eye exams every 1-2 years after age 40, and annually after age 60. Those with risk factors such as family history, diabetes, or African American ethnicity should begin screening earlier and more frequently.",
    swahili: {
      overview:
        "Glaucoma ni kikundi cha hali za macho zinazoharibu neva ya kuona, ambayo afya yake ni muhimu kwa uwezo mzuri wa kuona. Uharibifu huu mara nyingi unasababishwa na shinikizo la juu la kipekee katika jicho lako. Glaucoma ni moja ya sababu kuu za upofu kwa watu wenye umri zaidi ya miaka 60. Inaweza kutokea katika umri wowote lakini ni ya kawaida zaidi kwa watu wazima. Aina nyingi za glaucoma hazina ishara zozote za onyo. Athari ni ya polepole kiasi kwamba huenda usigundue mabadiliko katika kuona hadi hali iwe hatua ya juu. Kwa sababu upotevu wa uwezo wa kuona kutokana na glaucoma hauwezi kurejeshwa, ni muhimu kufanya uchunguzi mara kwa mara wa macho unaojumuisha vipimo vya shinikizo la jicho ili utambuzi ufanywe katika hatua zake za mapema na kutibiwa ipasavyo. Ikiwa glaucoma itatambuliwa mapema, upotevu wa uwezo wa kuona unaweza kupunguzwa au kuzuiliwa.",
      symptoms: [
        "Maeneo mapofu ya upofu katika kuona kwako wa kando (peripheral) au wa katikati, mara nyingi katika macho yote mawili",
        "Kuona kama kwenye tunuli katika hatua za juu",
        "Maumivu makali ya kichwa",
        "Maumivu ya jicho",
        "Kichefuchefu na kutapika",
        "Kuona kama kuna wingu",
        "Mabara ya nuru",
        "Uekundu wa jicho",
      ],
      causes: [
        "Shinikizo la juu la ndani ya jicho kutokana na kujengwa kwa maji katika jicho",
        "Kushindwa kupitisha maji ya aqueous humor kupitia trabecular meshwork",
        "Historia ya familia ya glaucoma",
        "Umri — watu wenye umri zaidi ya miaka 60 wako katika hatari zaidi",
        "Hali za kiafya kama vile kisukari, ugonjwa wa moyo, shinikizo la juu la damu, na sickle cell anemia",
        "Kupiga jicho mbali au karibu kupita kiasi",
        "Majeraha ya jicho au aina fulani za upasuaji wa jicho",
        "Matumizi ya muda mrefu ya dawa za kortikositeroidi, hasa majasho ya jicho",
        "Kabila — Waafrika Wamarekani, Waasia, na Wahispania wako katika hatari kubwa zaidi",
      ],
      treatments: [
        "Majasho ya daktari ya kupunguza shinikizo la ndani ya jicho",
        "Dawa za kumeza kama vile carbonic anhydrase inhibitors",
        "Laser trabeculoplasty kuboresha kupitisha maji",
        "Laser iridotomy kwa glaucoma ya kufunga pembe",
        "Upasuaji wa glaucoma wenye kuingilia kidogo (MIGS)",
        "Trabeculectomy kutengeneza njia mpya ya kupitisha maji",
        "M tubes (shunts) kupitisha maji ya ziada",
        "Mchakato wa cyclodestructive kupunguza utengenezwaji wa maji",
      ],
      whenToSeeDoctor:
        "Tafuta matibabu ya haraka ikiwa unapata maumivu ghafla makali ya jicho, maumivu ya kichwa, kuona kama kuna wingu, mabara ya nuru, au kichefuchefu na kutapika — hizi zinaweza kuwa ishara za glaucoma ya kufunga pembe ya ghafla, ambayo ni dharura ya kiafya. Vinginevyo, watu wazima wanapaswa kufanya uchunguzi kamili wa macho kila mwaka 1-2 baada ya umri wa miaka 40, na kila mwaka baada ya umri wa miaka 60. Wale wenye sababu za hatari kama historia ya familia, kisukari, au mtu Mwafrika Mmarekani wanapaswa kuanza ukaguzi mapema na mara nyingi zaidi.",
    },
  },
  {
    slug: "keratoconus",
    name: "Keratoconus",
    shortDesc: "An eye disease that causes the cornea to thin and bulge into a cone-like shape, distorting vision.",
    overview:
      "Keratoconus is an eye disease that affects the cornea — the clear, dome-shaped front surface of the eye. In keratoconus, the normally round cornea thins and begins to bulge into a cone-like shape. This abnormal shape prevents light from focusing correctly on the retina, causing distorted and blurred vision. Keratoconus typically affects both eyes and usually begins in the teenage years or early 20s, then gradually worsens over 10-20 years before stabilizing. The exact cause is unknown, but it is believed to involve a combination of genetic and environmental factors. Early stages can be managed with glasses or soft contact lenses, but as the condition progresses, specialized contact lenses or surgery may be required.",
    symptoms: [
      "Blurred or distorted vision",
      "Increased sensitivity to bright light and glare",
      "Difficulty with night driving",
      "Frequent changes in eyeglass prescriptions",
      "Sudden worsening or clouding of vision",
      "Ghost images or multiple images in one eye",
      "Eye strain or headaches",
      "A cone-shaped appearance of the cornea (visible on examination)",
    ],
    causes: [
      "Genetic predisposition — approximately 10% of patients have a family member with the condition",
      "Excessive eye rubbing, especially in people with allergies",
      "Connective tissue disorders such as Ehlers-Danlos syndrome or Marfan syndrome",
      "Down syndrome",
      "Chronic eye irritation",
      "Hormonal changes during puberty and pregnancy",
      "Oxidative stress causing weakness in corneal tissue",
      "Certain ethnic backgrounds (higher prevalence in Middle Eastern, South Asian, and Mediterranean populations)",
    ],
    treatments: [
      "Eyeglasses or soft contact lenses for early-stage keratoconus",
      "Rigid gas permeable (RGP) contact lenses to provide a smooth refractive surface",
      "Hybrid contact lenses with a rigid center and soft skirt",
      "Scleral contact lenses that vault over the cornea",
      "Corneal cross-linking (CXL) to strengthen corneal tissue and halt progression",
      "Intacs (corneal inserts) to flatten the cornea",
      "Topography-guided PRK laser surgery in select cases",
      "Deep anterior lamellar keratoplasty (DALK) or full corneal transplant in advanced cases",
    ],
    whenToSeeDoctor:
      "You should see an eye specialist if you experience rapid changes in vision, increasing astigmatism, or symptoms that cannot be corrected with regular glasses. Early diagnosis is crucial because treatments like corneal cross-linking are most effective when performed before the condition becomes advanced. Children of parents with keratoconus should have regular eye exams starting in their early teens, as early detection allows for timely intervention.",
    swahili: {
      overview:
        "Keratoconus ni ugonjwa wa jicho unaouathiri cornea — uso wa mbele wa jicho unaoweza kuonekana wenye umbo la kuba. Katika keratoconus, cornea iliyokuwa duara kwa kawaida hupungua unene na kuanza kutoa nje kwenye umbo la piramidi. Umbo huu usio wa kawaida huwazuia nuru kuzingatia vizuri kwenye retina, ikisababisha kuona kama kuna wingu na kupotoka. Keratoconus kwa kawaida huathiri macho yote mawili na kwa kawaida huanza katika miaka ya vijana au miaka ya 20 mapema, kisha huzidi kuwa mbaya polepole kwa miaka 10-20 kabla ya kustahimilika. Sababu halisi haijulikani, lakini inaaminiwa kuhusisha mchanganyiko wa sababu za urithi na mazingira. Hatua za mapema zinaweza kusimamiwa na miwani au lens za mawasiliano laini, lakini kadri hali inavyoendelea, lens za mawasiliano maalum au upasuaji unaweza kuhitajika.",
      symptoms: [
        "Kuona kama kuna wingu au kupotoka",
        "Kuhisia mwanga mwingi na mng'ao zaidi",
        "Ugumu wa kuendesha gari usiku",
        "Mabadiliko ya mara kwa mara ya dawa za miwani",
        "Kuwa mbaya ghafla au kuvimbiwa kwa kuona",
        "Picha za ghost au picha nyingi katika jicho moja",
        "Mashaka ya macho au maumivu ya kichwa",
        "Kuonekana kwa cornea yenye umbo la piramidi (kuonekana kwa uchunguzi)",
      ],
      causes: [
        "Urithi wa kuzaliwa nao — asilimia 10 ya wagonjwa wana mwanafamilia mwenye hali hii",
        "Kuchubua jicho kupita kiasi, hasa kwa watu wenye viambukizo",
        "Magonjwa ya tishu za kuunganisha kama vile Ehlers-Danlos syndrome au Marfan syndrome",
        "Down syndrome",
        "Uchokozi wa muda mrefu wa jicho",
        "Mabadiliko ya homoni wakati wa kubalehe na mimba",
        "Msongo wa oxidative ukisababisha udhaifu katika tishu ya cornea",
        "Mazingira fulani ya kikabila (watu wengi zaidi katika watu wa Mashariki ya Kati, Asia Kusini, na Mediterranean)",
      ],
      treatments: [
        "Miwani au lens za mawasiliano laini kwa keratoconus ya hatua ya mapema",
        "Lens za mawasiliano zenye uwezo wa kupitisha hewa (RGP) kutoa uso laini wa kupinda",
        "Lens za mawasiliano za hybrid zenye kituo gumu na sketi laini",
        "Lens za mawasiliano za scleral zinazovuka juu ya cornea",
        "Kuunganisha tishu ya cornea (CXL) kuimarisha tishu ya cornea na kusimamisha kuendelea",
        "Intacs (vijisugulu vya cornea) kupunguza cornea",
        "Upasuaji wa laser wa PRK uliosaidiwa na topography katika kesi chache",
        "Deep anterior lamellar keratoplasty (DALK) au uhamisho kamili wa cornea katika kesi zilizoendelea",
      ],
      whenToSeeDoctor:
        "Unapaswa kuona mtaalamu wa macho ikiwa unapata mabadiliko ya haraka ya kuona, kuongezeka kwa astigmatism, au dalili ambazo haziwezi kurekebishwa na miwani ya kawaida. Utambuzi mapema ni muhimu kwani matibabu kama vile kuunganisha tishu ya cornea yanafaa zaidi yanapofanywa kabla ya hali kuwa ya juu. Watoto wa wazazi wenye keratoconus wanapaswa kufanya uchunguzi mara kwa mara wa macho kuanzia katika miaka yao ya vijana, kwani ugunduzi mapema huruhusu kuingilia kwa wakati.",
    },
  },
  {
    slug: "low-vision",
    name: "Low Vision",
    shortDesc: "A visual impairment that cannot be fully corrected with standard eyeglasses, contact lenses, or surgery.",
    overview:
      "Low vision is a visual impairment that cannot be fully corrected with standard eyeglasses, contact lenses, medication, or surgery. It involves partial sight, such as blurred vision, blind spots, or tunnel vision, making everyday tasks difficult. Low vision is not the same as blindness; people with low vision still have some useful sight. It is most common in adults over 65 due to age-related eye conditions such as macular degeneration, glaucoma, and diabetic retinopathy. However, it can also affect younger people due to inherited conditions, eye injuries, or other diseases. With the right low vision aids, rehabilitation training, and support, people with low vision can maintain independence and continue many of their daily activities.",
    symptoms: [
      "Difficulty reading, even with standard glasses",
      "Problems recognizing faces",
      "Trouble seeing objects at a distance",
      "Difficulty distinguishing colors",
      "Poor night vision or trouble adjusting to different lighting",
      "Loss of peripheral (side) vision",
      "Need for bright light when reading or doing close work",
      "Glare sensitivity",
    ],
    causes: [
      "Age-related macular degeneration (AMD)",
      "Glaucoma",
      "Diabetic retinopathy",
      "Cataracts (when surgery is not possible or effective)",
      "Retinitis pigmentosa and other inherited retinal diseases",
      "Optic nerve damage from stroke or trauma",
      "Eye injuries",
      "Brain injuries affecting visual processing",
      "Albinism",
    ],
    treatments: [
      "Magnifying devices for reading and close work",
      "Electronic video magnifiers (CCTV or digital magnifiers)",
      "Large-print books, audiobooks, and screen-reading software",
      "High-contrast and specialized lighting solutions",
      "Telescopic lenses for distance viewing",
      "Orientation and mobility training",
      "Adaptive daily living skills training",
      "Counseling and support groups",
      "Treatment of the underlying eye condition where possible",
    ],
    whenToSeeDoctor:
      "Schedule an appointment with a low vision specialist if you find that regular glasses no longer help with everyday tasks, if you struggle to read, recognize faces, or navigate your environment. Early referral to a low vision rehabilitation program can significantly improve your quality of life and help you adapt to vision changes. Even if your eye doctor has told you that nothing more can be done for your eye condition, a low vision specialist can offer tools and strategies to help you make the most of your remaining vision.",
    swahili: {
      overview:
        "Uwezo wa kuona chini ni upungufu wa kuona ambao hauwezi kurekebishwa kabisa kwa miwani ya kawaida, lens za mawasiliano, dawa, au upasuaji. Unahusisha kuona sehemu, kama vile kuona kama kuna wingu, maeneo mapofu, au kuona kama kwenye tunuli, ikifanya shughuli za kila siku kuwa ngumu. Uwezo wa kuona chini sio sawa na upofu; watu wenye uwezo wa kuona chini bado wana kuona fulani. Ni ya kawaida zaidi kwa watu wazima wenye umri zaidi ya miaka 65 kutokana na hali za macho zinazohusiana na umri kama vile kuharibika kwa macula, glaucoma, na ugonjwa wa retina wa kisukari. Hata hivyo, inaweza pia kuathiri watu wadogo kutokana na hali zilizoorodheshwa, majeraha ya jicho, au magonjwa mengine. Kwa vifaa sahihi vya kuona chini, mafunzo ya urekebishaji, na msaada, watu wenye uwezo wa kuona chini wanaweza kudumisha uhuru na kuendelea na shughuli nyingi za kila siku.",
      symptoms: [
        "Ugumu wa kusoma, hata kwa miwani ya kawaida",
        "Matatizo ya kutambua nyuso",
        "Shida ya kuona vitu mbali",
        "Ugumu wa kutofautisha rangi",
        "Kuona dhaifu usiku au shida ya kurekebisha taa tofauti",
        "Upotevu wa kuona wa kando (peripheral)",
        "Haja ya nuru kali wakati wa kusoma au kufanya kazi karibu",
        "Kuhisia mng'ao",
      ],
      causes: [
        "Kuharibika kwa macula kutokana na umri (AMD)",
        "Glaucoma",
        "Ugonjwa wa retina wa kisukari",
        "Cataracts (wakati upasuaji hauwezekani au haufai)",
        "Retinitis pigmentosa na magonjwa mengine ya retina yaliyoorodheshwa",
        "Uharibifu wa neva ya kuona kutokana na kiharusi au majeraha",
        "Majeraha ya jicho",
        "Majeraha ya ubongo yanayoathiri usindikaji wa kuona",
        "Albinism",
      ],
      treatments: [
        "Vifaa vya kukuza kwa kusoma na kazi karibu",
        "Vikukuza vya video vya kielektroniki (CCTV au vikukuza vya kidigitali)",
        "Vitabu vya herufi kubwa, vitabu vya sauti, na programu za kusoma skrini",
        "Suluhisho za taa za tofauti kubwa na maalum",
        "Lens za telescope kwa kutazama mbali",
        "Mafunzo ya mwelekeo na uwezo wa kwenda",
        "Mafunzo ya stadi za kustahimili za kila siku",
        "Ushauri na vikundi vya msaada",
        "Matibabu ya hali ya msingi ya jicho iwezekanavyo",
      ],
      whenToSeeDoctor:
        "Panga miadi na mtaalamu wa kuona chini ikiwa unagundua kuwa miwani ya kawaida haisaidii tena katika shughuli za kila siku, ikiwa unashindwa kusoma, kutambua nyuso, au kupitia mazingira yako. Rufaa mapema kwa programu ya urekebishaji wa kuona chini inaweza kuboresha sana ubora wa maisha yako na kukusaidia kurekebisha mabadiliko ya kuona. Hata ikiwa daktari wako wa macho amekwambia kuwa hakuna chochote zaidi kinachoweza kufanyika kwa hali yako ya jicho, mtaalamu wa kuona chini anaweza kutoa zana na mikakati ya kukusaidia kutumia vizuri uwezo wako uliosalia wa kuona.",
    },
  },
  {
    slug: "retina-detachment",
    name: "Retina Detachment",
    shortDesc: "A serious condition where the retina pulls away from the tissue supporting it, threatening vision.",
    overview:
      "Retinal detachment is a serious eye condition that occurs when the retina — the light-sensitive layer of tissue at the back of the eye — pulls away from its normal position. When the retina becomes detached, it is separated from its underlying layer of blood vessels that provides oxygen and nourishment. The longer retinal detachment goes untreated, the greater the risk of permanent vision loss in the affected eye. Retinal detachment is considered a medical emergency. Anyone experiencing symptoms of retinal detachment should seek immediate ophthalmic care. With prompt treatment, particularly within the first 24 hours, the chances of preserving vision are significantly improved.",
    symptoms: [
      "The sudden appearance of many floaters — tiny specks that seem to drift through your field of vision",
      "Flashes of light in one or both eyes (photopsia)",
      "Blurred vision",
      "Gradually reduced side (peripheral) vision",
      "A curtain-like shadow over your visual field",
      "Straight lines that appear curved",
      "Loss of central vision in severe cases",
    ],
    causes: [
      "Rhegmatogenous retinal detachment — caused by a hole or tear in the retina allowing fluid to pass through",
      "Tractional retinal detachment — caused by scar tissue on the retina's surface contracting",
      "Exudative retinal detachment — caused by fluid accumulating beneath the retina without holes or tears",
      "Aging and vitreous gel shrinkage (posterior vitreous detachment)",
      "Severe eye injury or trauma",
      "Previous eye surgery, especially cataract surgery",
      "Extreme nearsightedness (high myopia)",
      "Family history of retinal detachment",
      "Degenerative conditions of the retina such as lattice degeneration",
    ],
    treatments: [
      "Laser surgery (photocoagulation) to seal retinal tears",
      "Cryopexy (freezing treatment) to seal retinal breaks",
      "Pneumatic retinopexy — injecting a gas bubble into the eye to push the retina back into place",
      "Scleral buckle surgery — placing a silicone band around the eye to indent the wall and relieve traction",
      "Vitrectomy — removing the vitreous gel and replacing it with a gas bubble or silicone oil",
      "Postoperative positioning to keep the gas bubble in the correct location",
      "Monitoring and follow-up care to ensure proper healing",
    ],
    whenToSeeDoctor:
      "Retinal detachment is a medical emergency. If you experience sudden onset of floaters, flashes of light, or a curtain-like shadow over your vision, seek emergency eye care immediately. Do not wait to see if symptoms improve on their own. The sooner treatment is administered, the better the visual outcome. Even if symptoms seem to subside, you should still be evaluated by an ophthalmologist, as these can be warning signs of an impending detachment.",
    swahili: {
      overview:
        "Kutengana kwa retina ni hali hatari ya jicho inayotokea wakati retina — safu yenye tishu inayohisi nuru nyuma ya jicho — inatoka kutoka mahali pake halisi. Wakati retina inapotengana, inatenganishwa na safu yake ya chini ya mishipa ya damu inayotoa oksijeni na lishe. Kwa muda mrefu kutengana kwa retina kitaendelea bila matibabu, ndivyo hatari ya upotevu wa kudumu wa uwezo wa kuona katika jicho lililoathirika. Kutengana kwa retina kinahesabiwa kama dharura ya kiafya. Mtu yeyote anayepata dalili za kutengana kwa retina anapaswa kutafuta huduma ya haraka ya macho. Kwa matibabu ya haraka, hasa ndani ya masaa 24 ya kwanza, nafasi za kuhifadhi uwezo wa kuona zinaongezeka sana.",
      symptoms: [
        "Kuonekana ghafla kwa floaters nyingi — vidudu vidogo vinavyoonekana kuzunguka katika uwanja wako wa kuona",
        "Miale ya nuru katika jicho moja au macho yote mawili (photopsia)",
        "Kuona kama kuna wingu",
        "Upungufu wa kuona wa kando (peripheral) polepole",
        "Kivuli kama pazia juu ya uwanja wako wa kuona",
        "Mistari mnyoofu inayoonekana yenye mviringo",
        "Upotevu wa kuona wa katikati katika kesi kali",
      ],
      causes: [
        "Kutengana kwa retina kwa njia ya rhegmatogenous — kusababishwa na tundu au jeraha katika retina likiruhusu maji kupitia",
        "Kutengana kwa retina kwa njia ya traction — kusababishwa na tishu ya mafuta kwenye uso wa retina ikinyonya",
        "Kutengana kwa retina kwa njia ya exudative — kusababishwa na maji kukusanyika chini ya retina bila tundu au jeraha",
        "Kuzeeka na kupungua kwa jeli ya vitreous (kutengana kwa vitreous nyuma)",
        "Majeraha makali ya jicho",
        "Upasuaji wa jicho uliopita, hasa upasuaji wa cataract",
        "Kupiga jicho karibu kupita kiasi (myopia ya juu)",
        "Historia ya familia ya kutengana kwa retina",
        "Hali za kuharibika kwa retina kama vile lattice degeneration",
      ],
      treatments: [
        "Upasuaji wa laser (photocoagulation) kufunga jeraha za retina",
        "Cryopexy (matibabu ya kugandisha) kufunga mapasuko ya retina",
        "Pneumatic retinopexy — kuingiza kimbungu la gesi ndani ya jicho kusukuma retina kurudi mahali pake",
        "Upasuaji wa scleral buckle — kuweka ukanda wa silicone jicho kuziba ukuta na kupunguza mvutano",
        "Vitrectomy — kuondoa jeli ya vitreous na kuichukua nafasi na kimbungu la gesi au mafuta ya silicone",
        "Kupanga mwili baada ya upasuaji kuweka kimbungu la gesi mahali sahihi",
        "Ufuatiliaji na matunzo ya ufuatiliaji kuhakikisha kupona kwa kufaa",
      ],
      whenToSeeDoctor:
        "Kutengana kwa retina ni dharura ya kiafya. Ikiwa unapata kuanza ghafla kwa floaters, miale ya nuru, au kivuli kama pazia juu ya kuona kwako, tafuta huduma ya haraka ya macho mara moja. Usisubiri kuona ikiwa dalili zitaboreka peke yake. Kadri matibabu yanavyotolewa haraka, ndivyo matokeo ya kuona yanavyokuwa bora. Hata ikiwa dalili zinaonekana kupungua, bado unapaswa kuchunguzwa na ophthalmologist, kwani hizi zinaweza kuwa ishara za kutengana karibuni.",
    },
  },
  {
    slug: "retinal-vein-occlusion",
    name: "Retinal Vein Occlusion",
    shortDesc: "A blockage of the small veins that carry blood away from the retina, causing vision loss.",
    overview:
      "Retinal vein occlusion (RVO) is a common vascular disorder of the retina and the second most common cause of vision loss from retinal vascular disease after diabetic retinopathy. It occurs when one of the veins that carry blood away from the retina becomes blocked, causing blood and fluid to back up and leak into the retina. This leads to swelling (macular edema), reduced blood flow, and vision loss. There are two main types: central retinal vein occlusion (CRVO), which affects the main retinal vein, and branch retinal vein occlusion (BRVO), which affects one of the smaller branch veins. RVO is more common in people over 60 and is often associated with high blood pressure, diabetes, glaucoma, and cardiovascular disease.",
    symptoms: [
      "Sudden, painless blurring or loss of vision in one eye",
      "Visual distortion or metamorphopsia",
      "Floaters in the field of vision",
      "Partial or complete vision loss depending on the severity and location of the blockage",
      "In some cases, symptoms may develop gradually over days or weeks",
      "Changes in color perception",
    ],
    causes: [
      "High blood pressure (hypertension) — the most common risk factor",
      "Atherosclerosis (hardening and narrowing of arteries)",
      "Diabetes mellitus",
      "Glaucoma",
      "Hyperlipidemia (high cholesterol)",
      "Blood clotting disorders",
      "Obstruction from adjacent hardened arteries compressing the vein",
      "Smoking",
      "Age over 60 years",
      "Inflammatory conditions such as vasculitis",
    ],
    treatments: [
      "Anti-VEGF injections (e.g., ranibizumab, aflibercept) to reduce macular edema",
      "Corticosteroid injections or implants (e.g., dexamethasone implant)",
      "Laser photocoagulation to seal leaking blood vessels",
      "Panretinal photocoagulation for neovascularization",
      "Management of underlying risk factors (blood pressure, diabetes, cholesterol)",
      "Anticoagulant or antiplatelet therapy in select cases",
      "Regular monitoring with OCT scans to assess treatment response",
      "Low vision aids for persistent vision loss",
    ],
    whenToSeeDoctor:
      "Seek immediate ophthalmic evaluation if you experience sudden painless vision loss or blurring in one eye. While retinal vein occlusion itself is not an emergency requiring same-day surgery, prompt diagnosis and treatment within days to weeks can significantly improve outcomes. Additionally, because RVO is often a sign of systemic vascular disease, your doctor may recommend evaluation by an internist or cardiologist to assess and manage underlying cardiovascular risk factors.",
    swahili: {
      overview:
        "Kuziba kwa mishipa ya damu ya retina (RVO) ni ugonjwa wa kawaida wa mishipa ya damu wa retina na sababu ya pili ya kawaida zaidi ya upotevu wa uwezo wa kuona kutokana na ugonjwa wa mishipa ya damu wa retina baada ya ugonjwa wa retina wa kisukari. Hutokea wakati moja ya mishipa ya damu inayochukua damu kutoka kwa retina inazibwa, ikisababisha damu na maji kurudi nyuma na kuvuja katika retina. Hii husababisha kuvimba (macular edema), kupungua kwa mtiririko wa damu, na upotevu wa uwezo wa kuona. Kuna aina kuu mbili: kuziba kwa mishipa kuu ya damu ya retina (CRVO), inayoaffect mishipa kuu ya retina, na kuziba kwa tawi la mishipa ya damu ya retina (BRVO), inayoaffect moja ya mishipa midogo ya tawi. RVO ni ya kawaida zaidi kwa watu wenye umri zaidi ya miaka 60 na mara nyingi inahusishwa na shinikizo la juu la damu, kisukari, glaucoma, na ugonjwa wa moyo na mishipa ya damu.",
      symptoms: [
        "Kupata waziwazi ghafla au upotevu wa uwezo wa kuona bila maumivu katika jicho moja",
        "Kupotoka kwa kuona au metamorphopsia",
        "Floaters katika uwanja wa kuona",
        "Upotevu wa sehemu au wa kila mahali wa kuona kulingana na ukali na mahali pa kuziba",
        "Katika kesi zingine, dalili zinaweza kukua polepole kwa siku au wiki",
        "Mabadiliko katika hisia ya rangi",
      ],
      causes: [
        "Shinikizo la juu la damu (hypertension) — sababu ya kawaida zaidi ya hatari",
        "Atherosclerosis (kuganda na kupungua kwa mishipa ya damu)",
        "Kisukari",
        "Glaucoma",
        "Hyperlipidemia (kolesterol ya juu)",
        "Magonjwa ya kuganda damu",
        "Kuzibiwa kutokana na mishipa ya damu iliyoganda karibu ikisukuma mishipa ya damu",
        "Kuvuta sigara",
        "Umri zaidi ya miaka 60",
        "Hali za uvimbi kama vile vasculitis",
      ],
      treatments: [
        "Sindano za anti-VEGF (mfano, ranibizumab, aflibercept) kupunguza kuvimba kwa macula",
        "Sindano za corticosteroid au vifaa vya kuingizwa (mfano, kitanzi cha dexamethasone)",
        "Laser photocoagulation kufunga mishipa ya damu inayovuja",
        "Panretinal photocoagulation kwa neovascularization",
        "Usimamizi wa sababu za hatari za msingi (shinikizo la damu, kisukari, kolesterol)",
        "Tiba ya kupunguza kuganda damu au antiplatelet katika kesi chache",
        "Ufuatiliaji mara kwa mara na uchunguzi wa OCT kutathmini jibu la matibabu",
        "Vifaa vya kuona chini kwa upotevu wa kuana unaodumu",
      ],
      whenToSeeDoctor:
        "Tafuta tathmini ya haraka ya macho ikiwa unapata upotevu ghafla wa uwezo wa kuona bila maumivu au kupata waziwazi katika jicho moja. Wakati kuziba kwa mishipa ya damu ya retina sio dharura inayohitaji upasuaji siku hiyo hiyo, utambuzi na matibabu ya haraka ndani ya siku hadi wiki zinaweza kuboresha matokeo sana. Zaidi ya hayo, kwa sababu RVO mara nyingi ni ishara ya ugonjwa wa mishipa ya damu wa mwili mzima, daktari wako anaweza kushauri tathmini na daktari wa magonjwa ya ndani au kardiologisi kutathmini na kusimamisha sababu za hatari za moyo na mishipa ya damu.",
    },
  },
  {
    slug: "tear-duct-obstruction",
    name: "Tear Duct Obstruction",
    shortDesc: "A blockage in the drainage system of the eye that prevents tears from draining normally.",
    overview:
      "Tear duct obstruction, also known as nasolacrimal duct obstruction or blocked tear duct, is a condition in which the drainage system for tears is partially or completely blocked. Tears normally drain from the eye surface through tiny openings in the eyelids (puncta), then through small canals into the lacrimal sac and down the nasolacrimal duct into the nose. When this pathway is blocked, tears cannot drain normally, causing watery eyes, irritation, and an increased risk of infection. Tear duct obstruction can affect people of all ages but is particularly common in newborns, affecting up to 20% of infants. In adults, it is often caused by age-related changes, infections, or nasal conditions.",
    symptoms: [
      "Excessive tearing (epiphora) even when not crying",
      "Redness of the white part of the eye",
      "Recurrent eye infections or conjunctivitis",
      "Swelling and pain near the corner of the eye (lacrimal sac infection / dacryocystitis)",
      "Discharge of mucus or pus from the eye",
      "Crusting of the eyelids",
      "Blurred vision from excess tears",
      "A feeling of fullness or pressure near the eye",
    ],
    causes: [
      "Congenital blockage — a thin membrane at the end of the tear duct that doesn't open at birth (common in infants)",
      "Age-related narrowing or closure of the tear duct",
      "Infections or chronic inflammation of the tear drainage system",
      "Nasal polyps or tumors obstructing the duct",
      "Facial injuries or trauma affecting the tear drainage pathway",
      "Previous nasal or sinus surgery",
      "Certain medications such as topical glaucoma eye drops",
      "Radiation therapy to the face",
      "Sarcoidosis or other granulomatous diseases",
    ],
    treatments: [
      "Massage of the lacrimal sac in infants (often resolves spontaneously by age 1)",
      "Warm compresses to relieve swelling and discomfort",
      "Antibiotic eye drops or ointments for infections",
      "Oral antibiotics for dacryocystitis (lacrimal sac infection)",
      "Probing of the tear duct — a thin wire is passed through the duct to open the blockage",
      "Balloon catheter dilation to widen a narrowed tear duct",
      "Intubation with silicone stents to keep the duct open",
      "Dacryocystorhinostomy (DCR) surgery to create a new drainage pathway into the nose",
      "Conjunctivodacryocystorhinostomy (CDCR) with Jones tube for severe blockages",
    ],
    whenToSeeDoctor:
      "Consult an eye doctor if you have persistent watery eyes, recurrent eye infections, or swelling and tenderness near the inner corner of your eye. For infants, most blocked tear ducts clear on their own by 6-12 months of age. However, if tearing persists beyond the first year, or if there is significant discharge, redness, or swelling, the child should be evaluated by a pediatric ophthalmologist. Adults with symptoms of tear duct obstruction should seek evaluation, as treatment can provide significant relief and prevent recurrent infections.",
    swahili: {
      overview:
        "Kuziba kwa njia ya machozi, pia julikana kama kuziba kwa njia ya nasolacrimal au kuziba kwa njia ya machozi, ni hali ambayo mfumo wa kupitisha maji ya machozi umefungwa sehemu au kabisa. Machozi kwa kawaida hutoka kwa uso wa jicho kupitia vinyue vidogo vya viwembe vya macho (puncta), kisha kupitia mabwawa madogo hadi mfuko wa machozi na chini ya njia ya nasolacrimal hadi kwenye pua. Wakati njia hii imezibwa, machozi hayawezi kupitisha kwa kawaida, ikisababisha macho yenye maji, usumbufu, na hatari iliyoongezeka ya maambukizo. Kuziba kwa njia ya machozi unaweza kuathiri watu wa rika zote lakini ni la kawaida sana kwa watoto wachanga, ikiathiri hadi asilimia 20 ya watoto wachanga. Kwa watu wazima, mara nyingi husababishwa na mabadiliko yanayohusiana na umri, maambukizo, au hali za pua.",
      symptoms: [
        "Machozi mengi (epiphora) hata wakati hulia",
        "Uekundu wa sehemu nyeupe ya jicho",
        "Maambukizo ya mara kwa mara ya jicho au conjunctivitis",
        "Kuvimba na maumivu karibu na kona ya jicho (maambukizo ya mfuko wa machozi / dacryocystitis)",
        "Jasho la tegili au pusu kutoka kwa jicho",
        "Kugandamana kwa viwembe vya macho",
        "Kuona kama kuna wingu kutokana na machozi mengi",
        "Hisia ya ujazo au shinikizo karibu na jicho",
      ],
      causes: [
        "Kuziba kwa kuzaliwa — tishu nyembamba mwisho wa njia ya machozi ambayo haifunguli wakati wa kuzaliwa (kawaida kwa watoto wachanga)",
        "Kupungua au kufungwa kwa njia ya machozi kutokana na umri",
        "Maambukizo au uvimbi wa muda mrefu wa mfumo wa kupitisha maji ya machozi",
        "Polyps za pua au vimbe vinavyozuia njia",
        "Majeraha ya uso au trauma yanayoathiri njia ya kupitisha maji ya machozi",
        "Upasuaji uliopita wa pua au sinus",
        "Dawa fulani kama vile majasho ya jicho ya kupunguza shinikizo la glaucoma",
        "Tiba ya mionzi kwa uso",
        "Sarcoidosis au magonjwa mengine ya granulomatous",
      ],
      treatments: [
        "Kukanda mfuko wa machozi kwa watoto wachanga (mara nyingi hupona peke yake hadi umri wa mwaka 1)",
        "Compress za joto kupunguza kuvimba na usumbufu",
        "Majasho ya antibayotiki au mafuta kwa maambukizo",
        "Antibayotiki za kumeza kwa dacryocystitis (maambukizo ya mfuko wa machozi)",
        "Kuchunguza njia ya machozi — waya mwembamba hupitia kupitia njia kufungua kuziba",
        "Kupanua kwa catheter ya balloon kupanua njia ya machozi iliyopungua",
        "Kuwekwa kwa stents za silicone kudumisha njia wazi",
        "Upasuaji wa dacryocystorhinostomy (DCR) kutengeneza njia mpya ya kupitisha maji kwenye pua",
        "Conjunctivodacryocystorhinostomy (CDCR) na bomba la Jones kwa kuzibwa kali",
      ],
      whenToSeeDoctor:
        "Shauriana na daktari wa macho ikiwa una macho yenye maji ya kudumu, maambukizo ya mara kwa mara ya jicho, au kuvimba na usumbufu karibu na kona ya ndani ya jicho lako. Kwa watoto wachanga, njia nyingi zilizozibwa za machozi hufunguliwa peke yake hadi umri wa miezi 6-12. Hata hivyo, ikiwa machozi yaendelee baada ya mwaka wa kwanza, au ikiwa kuna jasho kubwa, uekundu, au kuvimba, mtoto anapaswa kuchunguzwa na ophthalmologist wa watoto. Watu wazima wenye dalili za kuziba kwa njia ya machozi wanapaswa kutafuta tathmini, kwani matibabu yanaweza kutoa nafuu kubwa na kuzuia maambukizo ya mara kwa mara.",
    },
  },
  {
    slug: "uveitis",
    name: "Uveitis",
    shortDesc: "Inflammation of the uvea, the middle layer of the eye, which can cause vision loss if untreated.",
    overview:
      "Uveitis is a form of eye inflammation that affects the uvea — the middle layer of tissue in the eye wall. The uvea consists of the iris (the colored part of the eye), the ciliary body (which produces the fluid inside the eye), and the choroid (which contains blood vessels). Uveitis can be acute or chronic and may affect one or both eyes. It is a leading cause of blindness and is particularly dangerous because many of its forms can develop rapidly and cause permanent vision loss. Uveitis can occur at any age, but it most commonly affects people between 20 and 60. Prompt diagnosis and treatment are critical to prevent complications such as glaucoma, cataracts, optic nerve damage, and retinal detachment.",
    symptoms: [
      "Eye redness",
      "Eye pain",
      "Light sensitivity (photophobia)",
      "Blurred vision",
      "Dark, floating spots in your field of vision (floaters)",
      "Decreased vision",
      "A white area over the colored part of the eye",
      "Headaches",
    ],
    causes: [
      "Autoimmune or inflammatory disorders such as rheumatoid arthritis, lupus, or sarcoidosis",
      "Infections including toxoplasmosis, herpes, syphilis, tuberculosis, or HIV",
      "Eye injuries or trauma",
      "Certain cancers that affect the eye, such as lymphoma",
      "Inflammatory bowel disease (Crohn's disease, ulcerative colitis)",
      "Multiple sclerosis",
      "Ankylosing spondylitis and other seronegative spondyloarthropathies",
      "Behçet's disease",
      "In many cases, the exact cause is unknown (idiopathic uveitis)",
    ],
    treatments: [
      "Corticosteroid eye drops to reduce inflammation",
      "Corticosteroid injections around or into the eye for more severe cases",
      "Oral corticosteroids for posterior uveitis or when eye drops are insufficient",
      "Immunosuppressive medications for severe or chronic cases",
      "Antibiotics or antiviral medications if an infection is the cause",
      "Mydriatic or cycloplegic eye drops to dilate the pupil and relieve pain",
      "Treatment of underlying systemic conditions",
      "Surgery in rare cases to implant a device that releases corticosteroids slowly",
    ],
    whenToSeeDoctor:
      "Seek immediate medical attention if you experience eye pain, redness, light sensitivity, or any sudden change in vision. Uveitis is a serious condition that requires prompt treatment by an ophthalmologist. Delays in treatment can lead to permanent vision loss. If you have an autoimmune disease or a known infection that can affect the eyes, regular monitoring by an eye specialist is essential, even if you have no current symptoms.",
    swahili: {
      overview:
        "Uveitis ni aina ya uvimbi wa jicho unaouathiri uvea — safu ya katikati ya tishu katika ukuta wa jicho. Uvea inajumuisha iris (sehemu ya rangi ya jicho), mwili wa ciliary (inayotengeneza maji ndani ya jicho), na choroid (inayojumuisha mishipa ya damu). Uveitis inaweza kuwa ya ghafla au ya muda mrefu na inaweza kuathiri jicho moja au macho yote mawili. Ni sababu kuu ya upofu na ni hatari haswa kwa sababu aina nyingi zake zinaweza kukua kwa kasi na kusababisha upotevu wa kudumu wa uwezo wa kuona. Uveitis inaweza kutokea katika umri wowote, lakini mara nyingi huathiri watu kati ya miaka 20 na 60. Utambuzi na matibabu ya haraka ni muhimu kuzuia matatizo kama vile glaucoma, cataracts, uharibifu wa neva ya kuona, na kutengana kwa retina.",
      symptoms: [
        "Uekundu wa jicho",
        "Maumivu ya jicho",
        "Kuhisia mwanga (photophobia)",
        "Kuona kama kuna wingu",
        "Madoadoa ya giza yanayozunguka katika uwanja wako wa kuona (floaters)",
        "Upungufu wa uwezo wa kuona",
        "Eneo jeupe juu ya sehemu ya rangi ya jicho",
        "Maumivu ya kichwa",
      ],
      causes: [
        "Magonjwa ya autoimmune au uvimbi kama vile rheumatoid arthritis, lupus, au sarcoidosis",
        "Maambukizo kikiwemo toxoplasmosis, herpes, kaswende, kifua kikuu, au VVU",
        "Majeraha ya jicho au trauma",
        "Saratani fulani zinazouathiri jicho, kama vile lymphoma",
        "Ugonjwa wa uvimbi wa utumbo (ugonjwa wa Crohn, colitis ya kuvimba)",
        "Multiple sclerosis",
        "Ankylosing spondylitis na spondyloarthropathies zingine za seronegative",
        "Ugonjwa wa Behçet",
        "Katika kesi nyingi, sababu halisi haijulikani (uveitis ya idiopathic)",
      ],
      treatments: [
        "Majasho ya corticosteroid kupunguza uvimbi",
        "Sindano za corticosteroid karibu au ndani ya jicho kwa kesi kali zaidi",
        "Corticosteroids za kumeza kwa uveitis ya nyuma au wakati majasho ya jicho hayatoshi",
        "Dawa za kupunguza kinga kwa kesi kali au za muda mrefu",
        "Antibayotiki au dawa za kupigana na virusi ikiwa maambukizo ni sababu",
        "Majasho ya mydriatic au cycloplegic kupanua mboni na kupunguza maumivu",
        "Matibabu ya hali za mwili mzima za msingi",
        "Upasuaji katika kesi chache kuweka kifaa kinachotoa corticosteroids polepole",
      ],
      whenToSeeDoctor:
        "Tafuta matibabu ya haraka ikiwa unapata maumivu ya jicho, uekundu, kuhisia mwanga, au mabadiliko yoyote ghafla ya kuona. Uveitis ni hali hatari inayohitaji matibabu ya haraka na ophthalmologist. Kuchelewa matibabu yanaweza kusababisha upotevu wa kudumu wa uwezo wa kuona. Ikiwa una ugonjwa wa autoimmune au maambukizo yanayojulikana yanayoweza kuathiri macho, ufuatiliaji mara kwa mara na mtaalamu wa macho ni muhimu, hata ikiwa huna dalili za sasa.",
    },
  },
];

export function getConditionBySlug(slug: string): EyeCondition | undefined {
  return eyeConditions.find((c) => c.slug === slug);
}

export function getAllConditionSlugs(): string[] {
  return eyeConditions.map((c) => c.slug);
}
